### ISSUE TITLE
Incorrect color when hovering store items

### ISSUE THREAD

**Issue by Fesiug** [Commenter25/userstyles#3]
The Xenia doesn't get colored on certain parts of the store! As seen when scrolling to the New & Trending, Top Sellers, etc part of the main home store page:
![image](https://user-images.githubusercontent.com/40924091/198869683-e7bf099e-898d-461c-bd0f-218da6c1422f.png)

**Comment by Commenter25** [comment]
The hovering issue has been fixed with 1.0.2. Thank you for the bug report!

I don't think you meant to show it, but that thing with the Windows and Mac icons not appearing is a Steam issue I hadn't encountered before. It seems sometimes their code tries to get icons that don't exist. I'm going to see how I can report this to Valve...
